name: Linux (dotnet build and test)

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  os-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version:  |
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
      - name: Restore dependencies
        run: |
          dotnet restore ./src/CSharp/EasyMicroservices.Serialization-net6.0.sln
          dotnet restore ./src/CSharp/EasyMicroservices.Serialization-net7.0.sln
          dotnet restore ./src/CSharp/EasyMicroservices.Serialization-net8.0.sln
      - name: Build
        run: |
          dotnet build ./src/CSharp/EasyMicroservices.Serialization-net6.0.sln --no-restore
          dotnet build ./src/CSharp/EasyMicroservices.Serialization-net7.0.sln --no-restore
          dotnet build ./src/CSharp/EasyMicroservices.Serialization-net8.0.sln --no-restore
      - name: Test
        run: |
          dotnet test ./src/CSharp/EasyMicroservices.Serialization-net6.0.sln --no-build --verbosity normal
          dotnet test ./src/CSharp/EasyMicroservices.Serialization-net7.0.sln --no-build --verbosity normal
          dotnet test ./src/CSharp/EasyMicroservices.Serialization-net8.0.sln --no-build --verbosity normal
